version: '3.8'

services:
  ai-agent-platform-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ai-agent-platform-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./prisma/dev.db
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev